M48
; DRILL file {KiCad 7.0.1-0} date 2023 April 24, Monday 13:38:07
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-24T13:38:07-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1-0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1378
%
G90
G05
T1
X6.378Y-2.4803
X6.378Y-4.7244
X8.5433Y-2.4803
X8.5433Y-4.7244
T0
M30
